version: '3'
services:
  frontend:
    image: ghcr.io/pinetree2/frontend:latest
    ports:
      - "80:80"
    networks:
      - app_net

  backend:
    image: ghcr.io/pinetree2/backend:latest
    ports:
      - "8082:8082"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
