name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
                
      - name: Install dependencies
        run: npm install

      - name: Build frontend Docker image
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          cd frontend
          docker build -t ghcr.io/${{ env.GHCR_USERNAME }}/frontend:latest .
          echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
          docker push ghcr.io/${{ env.GHCR_USERNAME }}/frontend:latest

      - name: Build backend Docker image
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          cd backend
          docker build -t ghcr.io/${{ env.GHCR_USERNAME }}/backend:latest .
          echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
          docker push ghcr.io/${{ env.GHCR_USERNAME }}/backend:latest

      - name: Deploy to cloud server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /path/to/docker-compose/directory
            docker-compose pull
            docker-compose up -d
